### PR TITLE
Expand/compress predicates + replace icon tabs with toggle button group

### PR DESCRIPTION
**Pull request by Salam-Dalloul**
- Expand/compress predicates accordion
- replace CustomIconTabs common component with Mui ToggleButtonGroup component

### CODE REVIEW

**Review by jrmartin — APPROVED** [review]
Looks good !

**Review by jrmartin — APPROVED** [review]
Looks good! Just needs to fix the conflict with the latest from development.

**Review by jrmartin — CHANGES_REQUESTED** [review]
Looks good! Just needs to fix the conflict with the latest from development.

**Review by Aiga115 — COMMENTED** [review]
Everything is good! Thanks @Salam-Dalloul  
I am just concerned about why the icons for predicate accordion has similar icons to expand and compress, because functionality wise it is wrong
image

**Comment by ddelpiano** [comment]
> Everything is good! Thanks @Salam-Dalloul I am just concerned about why the icons for predicate accordion has similar icons to expand and compress, because functionality wise it is wrong image

@Aiga115 moving this to the jira board to get the designer feedback. Thanks!

**Pull request merged**
