### PR TITLE
ILEX-47 Add a new term UI component

### PR DESCRIPTION
**Pull request by Aiga115**
Issue [#ILEX-47](https://metacell.atlassian.net/jira/software/c/projects/ILEX/boards/58?selectedIssue=ILEX-47)
Problem: Add a new term UI component
Solution: 
'Add new term' dialog ui is added

https://github.com/user-attachments/assets/4531e332-5d92-4241-ba74-e95d02cfaa92

### CODE REVIEW

**Comment by ddelpiano** [comment]
```
Uncaught TypeError: options.filter is not a function
    at useAutocomplete (chunk-BDYTYOO7.js?v=8af4d70e:617:13)
    at Autocomplete2 (chunk-QO2F4ZJX.js?v=8af4d70e:2099:7)
    at renderWithHooks (chunk-P3FVMTXM.js?v=8af4d70e:11568:26)
    at updateForwardRef (chunk-P3FVMTXM.js?v=8af4d70e:14345:28)
    at beginWork (chunk-P3FVMTXM.js?v=8af4d70e:15966:22)
    at beginWork$1 (chunk-P3FVMTXM.js?v=8af4d70e:19781:22)
    at performUnitOfWork (chunk-P3FVMTXM.js?v=8af4d70e:19226:20)
    at workLoopSync (chunk-P3FVMTXM.js?v=8af4d70e:19165:13)
    at renderRootSync (chunk-P3FVMTXM.js?v=8af4d70e:19144:15)
    at recoverFromConcurrentError (chunk-P3FVMTXM.js?v=8af4d70e:18764:28)
2AddNewTermDialog.jsx:181 getExistingIDs  TypeError: Cannot read properties of undefined (reading 'split')
    at index.ts:119:62
    at Array.map (<anonymous>)
    at index.ts:119:41
    at async fetchIds (AddNewTermDialog.jsx:179:21)
````

When creating a new term, searching for other ids.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
there is an error using the UI atm

**Comment by jrmartin** [comment]
> there is an error using the UI atm

This error is coming from a null pointer exception returned by the endpoint. 

@Aiga115 You can commit the local fix for it, which adds the conditional check on variables.

Modify this line : https://github.com/MetaCell/interlex/blob/devel/src/api/endpoints/index.ts#L119

Change 

`      let existingIds = terms?.results?.map( term => term.id.split("/").pop() );
`
      to 
      
`       let existingIds = terms?.results?.map( term => term.id?.split("/")?.pop() );`

**Comment by Aiga115** [comment]
> > there is an error using the UI atm
> 
> This error is coming from a null pointer exception returned by the endpoint.
> 
> @Aiga115 You can commit the local fix for it, which adds the conditional check on variables.
> 
> Modify this line : https://github.com/MetaCell/interlex/blob/devel/src/api/endpoints/index.ts#L119
> 
> Change
> 
> ` let existingIds = terms?.results?.map( term => term.id.split("/").pop() );` to
> 
> ` let existingIds = terms?.results?.map( term => term.id?.split("/")?.pop() );`

@jrmartin but this gets me to this condition
image

**Comment by jrmartin** [comment]
> ```
> Uncaught TypeError: options.filter is not a function
>     at useAutocomplete (chunk-BDYTYOO7.js?v=8af4d70e:617:13)
>     at Autocomplete2 (chunk-QO2F4ZJX.js?v=8af4d70e:2099:7)
>     at renderWithHooks (chunk-P3FVMTXM.js?v=8af4d70e:11568:26)
>     at updateForwardRef (chunk-P3FVMTXM.js?v=8af4d70e:14345:28)
>     at beginWork (chunk-P3FVMTXM.js?v=8af4d70e:15966:22)
>     at beginWork$1 (chunk-P3FVMTXM.js?v=8af4d70e:19781:22)
>     at performUnitOfWork (chunk-P3FVMTXM.js?v=8af4d70e:19226:20)
>     at workLoopSync (chunk-P3FVMTXM.js?v=8af4d70e:19165:13)
>     at renderRootSync (chunk-P3FVMTXM.js?v=8af4d70e:19144:15)
>     at recoverFromConcurrentError (chunk-P3FVMTXM.js?v=8af4d70e:18764:28)
> 2AddNewTermDialog.jsx:181 getExistingIDs  TypeError: Cannot read properties of undefined (reading 'split')
>     at index.ts:119:62
>     at Array.map (<anonymous>)
>     at index.ts:119:41
>     at async fetchIds (AddNewTermDialog.jsx:179:21)
> ```
> 
> When creating a new term, searching for other ids.

@ddelpiano I tested this branch locally and I'm not getting this error. Furthermore, I deployed this branch and I don't see the errors happening there either.

**Pull request merged**
