### PR TITLE
ILEX-69 Add new term last flow missing the id in the response to show in the last view, also add a button to show the term created

### PR DESCRIPTION
**Pull request by Aiga115**
Issue [#ILEX-69](https://metacell.atlassian.net/jira/software/c/projects/ILEX/boards/58?selectedIssue=ILEX-69)
Problem: Add new term last flow missing the id in the response to show in the last view, also add a button to show the term created
Solution: 
Add api to post the new term data and get id from response
Format this response to match with the Figma design 

image

### CODE REVIEW

**Comment by ddelpiano** [comment]
@Aiga115 this has conflicts to be resolved, I am not leaving comments about the review (I had a couple) since I imagine that my comments are about the outdated code that you already improved in the PR where you handle the response (and error) from the backend, if any. Thanks

**Review by jrmartin — CHANGES_REQUESTED** [review]
Hi @Aiga115 , there's some conflicts on this branch with devel branch, most likely after latest PR got merged.

**Review by jrmartin — APPROVED** [review]
Looks good to me !

**Review by jrmartin — CHANGES_REQUESTED** [review]
@Aiga115 There's new conflicts after merging a previous PR, please fix whenever you have a chance.

**Review by jrmartin — APPROVED** [review]

**Pull request merged**
