### PR TITLE
#61 My Dashboard UI implementation

### PR DESCRIPTION
**Pull request by Salam-Dalloul**
https://github.com/user-attachments/assets/fe87ba98-6f72-402d-98a4-92c0ade7debc

### CODE REVIEW

**Review by Aiga115 — COMMENTED** [review]
Great work @Salam-Dalloul! Just few points: 
1. The Chip 'Contributor' | 'Admin' is not as in Figma
image
2. I noticed that 'Show on page: ' select dropdown showing 24 option for data, but we don't have 24 options, IMO we don't need to show that
I think we connect it
3.  On term variant hover I see a button 'Add term to active ontology', however in Figma we don't have that, either for admin and contributor

Please feel free to comment, I migth be wrong on some points

**Comment by Salam-Dalloul** [comment]
> Great work @Salam-Dalloul! Just few points:
> 
> 1. The Chip 'Contributor' | 'Admin' is not as in Figma
>    image
> 2. I noticed that 'Show on page: ' select dropdown showing 24 option for data, but we don't have 24 options, IMO we don't need to show that
>    I think we connect it
> 3. On term variant hover I see a button 'Add term to active ontology', however in Figma we don't have that, either for admin and contributor
> 
> Please feel free to comment, I migth be wrong on some points

@Aiga115 fixed point 1,3 for point 2, what if we had more that 24 terms in the future?

**Comment by Aiga115** [comment]
> > Great work @Salam-Dalloul! Just few points:
> > 
> > 1. The Chip 'Contributor' | 'Admin' is not as in Figma
> >    image
> > 2. I noticed that 'Show on page: ' select dropdown showing 24 option for data, but we don't have 24 options, IMO we don't need to show that
> >    I think we connect it
> > 3. On term variant hover I see a button 'Add term to active ontology', however in Figma we don't have that, either for admin and contributor
> > 
> > Please feel free to comment, I migth be wrong on some points
> 
> @Aiga115 fixed point 1,3 for point 2, what if we had more that 24 terms in the future?

I see, thanks @Salam-Dalloul 
About the second point, i think we need to be able to select what we have, if we have 24 terms then we need to show that, but if we have less, the dropdown should be able to handle this case, what do you think?

**Comment by Salam-Dalloul** [comment]
> > > Great work @Salam-Dalloul! Just few points:
> > > 
> > > 1. The Chip 'Contributor' | 'Admin' is not as in Figma
> > >    image
> > > 2. I noticed that 'Show on page: ' select dropdown showing 24 option for data, but we don't have 24 options, IMO we don't need to show that
> > >    I think we connect it
> > > 3. On term variant hover I see a button 'Add term to active ontology', however in Figma we don't have that, either for admin and contributor
> > > 
> > > Please feel free to comment, I migth be wrong on some points
> > 
> > 
> > @Aiga115 fixed point 1,3 for point 2, what if we had more that 24 terms in the future?
> 
> I see, thanks @Salam-Dalloul About the second point, i think we need to be able to select what we have, if we have 24 terms then we need to show that, but if we have less, the dropdown should be able to handle this case, what do you think?

@ddelpiano could you please check the comments here? Thnx

**Comment by ddelpiano** [comment]
> > > > Great work @Salam-Dalloul! Just few points:
> > > > 
> > > > 1. The Chip 'Contributor' | 'Admin' is not as in Figma
> > > >    image
> > > > 2. I noticed that 'Show on page: ' select dropdown showing 24 option for data, but we don't have 24 options, IMO we don't need to show that
> > > >    I think we connect it
> > > > 3. On term variant hover I see a button 'Add term to active ontology', however in Figma we don't have that, either for admin and contributor
> > > > 
> > > > Please feel free to comment, I migth be wrong on some points
> > > 
> > > 
> > > @Aiga115 fixed point 1,3 for point 2, what if we had more that 24 terms in the future?
> > 
> > 
> > I see, thanks @Salam-Dalloul About the second point, i think we need to be able to select what we have, if we have 24 terms then we need to show that, but if we have less, the dropdown should be able to handle this case, what do you think?
> 
> @ddelpiano could you please check the comments here? Thnx

the 8/16/24 are an options to display more records in a single page, this should not be influenced by the fact that we have less or more records since pagination will take care of that when needed.
The implementation is good for me, we need to connect the UI to the backend but so far so good here. Thanks

**Pull request merged**
